language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy

script:
  - python test_pangram.py

after_success:
  - pip install pycodestyle pyflakes
  - pyflakes *.py
  - pycodestyle *.py

matrix:
  fast_finish: true
