language: python

python:
  - "3.6"
  - pypy-3.8

script:
  - python test_pangram.py

after_success:
  - pip install pycodestyle pyflakes
  - pyflakes *.py
  - pycodestyle *.py

matrix:
  fast_finish: true
