language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

script:
  - python test_pangram.py

after_success:
  - pip install pep8 pyflakes
  - pep8 *.py
  - pyflakes *.py

matrix:
  allow_failures:
    - python: 2.6
